sylius_grid:
    grids:
        odiseo_sylius_easy_post_plugin_easy_post_configuration:
            driver:
                name: doctrine/orm
                options:
                    class: "%odiseo_sylius_easy_post_plugin.model.easy_post_configuration.class%"
            sorting:
                createdAt: desc
            fields:
                name:
                    type: string
                    label: sylius.ui.name
                    sortable: ~
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    sortable: ~
                    options:
                        template: "@SyliusUi/Grid/Field/enabled.html.twig"
                createdAt:
                    type: datetime
                    label: sylius.ui.creation_date
                    sortable: ~
                    options:
                        format: d-m-Y H:i
            filters:
                name:
                    type: string
                    label: sylius.ui.name
                enabled:
                    type: boolean
                    label: sylius.ui.enabled
                createdAt:
                    type: date
                    label: sylius.ui.creation_date
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
