services:
    odiseo_sylius_easy_post_plugin.assigner.shipment:
        class: Odiseo\SyliusEasyPostPlugin\Assigner\ShipmentAssigner
        public: true
        arguments:
            - '@odiseo_sylius_easy_post_plugin.api.easy_post_client'

    odiseo_sylius_easy_post_plugin.assigner.shipment_rate:
        class: Odiseo\SyliusEasyPostPlugin\Assigner\ShipmentRateAssigner
        public: true
        arguments:
            - '@odiseo_sylius_easy_post_plugin.api.easy_post_client'
