imports:
    - { resource: services/api.yaml }
    - { resource: services/calculator.yaml }
    - { resource: services/checker.yaml }
    - { resource: services/event_listener.yaml }
    - { resource: services/form.yaml }
    - { resource: services/provider.yaml }
