
imports:
    - { resource: services/event_listener.yaml }
    - { resource: services/form.yaml }

parameters:
    easy_post.apikey: '%env(ODISEO_EASY_POST_APIKEY)%'
    odiseo_sylius_easy_post_plugin.service.easy_post.class: Odiseo\SyliusEasyPostPlugin\Service\EasyPostService
    odiseo_sylius_easy_post_plugin.shipping_calculator.easy_post.class: Odiseo\SyliusEasyPostPlugin\Shipping\EasyPostCalculator


services:
    odiseo_sylius_easy_post_plugin.service.easy_post:
        class: "%odiseo_sylius_easy_post_plugin.service.easy_post.class%"
        arguments: ["%easy_post.apikey%", "@request_stack"]
    odiseo_sylius_easy_post_plugin.shipping_calculator.easy_post:
        class: "%odiseo_sylius_easy_post_plugin.shipping_calculator.easy_post.class%"
        arguments: ["@odiseo_sylius_easy_post_plugin.service.easy_post", "@request_stack"]
        tags:
            - { name: "sylius.shipping_calculator", form_type: "Odiseo\\SyliusEasyPostPlugin\\Form\\Type\\Shipping\\EasyPostConfigurationType", calculator: "easy_post", label: "EasyPost" }
