sylius_resource:
    resources:
        odiseo_sylius_easy_post_plugin.easy_post_configuration:
            driver: doctrine/orm
            classes:
                model: Odiseo\SyliusEasyPostPlugin\Entity\EasyPostConfiguration
                interface: Odiseo\SyliusEasyPostPlugin\Entity\EasyPostConfigurationInterface
