winzou_state_machine:
    sylius_shipment:
        callbacks:
            after:
                odiseo_sylius_easy_post_plugin_assign_rate:
                    on: ["create"]
                    do: ["@odiseo_sylius_easy_post_plugin.assigner.shipment_rate", "assignRate"]
                    args: ["object"]
                odiseo_sylius_easy_post_plugin_create_shipment_tracking:
                    on: ["ship"]
                    do: ["@odiseo_sylius_easy_post_plugin.generator.shipment_tracking", "generate"]
                    args: ["object"]
